services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - '5678:5678'
    environment:
      - GENERIC_TIMEZONE=Europe/Kiev
      - ASTROLOGY_API_BASE_URL=${ASTROLOGY_API_BASE_URL}
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      # reset license on shutdown
      - N8N_LICENSE_DETACH_FLOATING_ON_SHUTDOWN=true
    volumes:
      - ./data/n8n_data:/home/node/.n8n
      - ..:/home/node/.n8n/nodes/node_modules/@astro-api/n8n-nodes-astrology
