services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - '5678:5678'
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
      - GENERIC_TIMEZONE=Europe/Kiev
      - ASTROLOGY_API_BASE_URL=${ASTROLOGY_API_BASE_URL}
    volumes:
      - ./data/n8n_data:/home/node/.n8n
      - ../dist:/home/node/.n8n/custom/n8n-nodes-astrology
